Add DialogueAct dataclass
iai-group/DialogueKit pull request #210
Opened 2023-03-01 09:00 UTC by NoB0

Create a dataclass to represent a dialogue act. Upon approval, `AnnotatedUtterance` should be refactored to include a list of dialogue acts instead of an intent and annotations.

Part of #157

2023-03-02 10:48 UTC, kbalog requested changes
Asking for an example in the file-level docstring.

2023-03-02 10:48 UTC, kbalog commented on dialoguekit/core/dialogue_act.py
> +"""Interface representing a dialogue act."""
Could you expand the description with two specific examples of dialogue acts? E.g., one with and one without annotations.

2023-03-07 10:50 UTC, kbalog approved these changes
Very nice! LGTM

2023-03-16 12:41 UTC, IKostric approved these changes
LGTM

2023-03-17 09:38 UTC, merged